FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app/authentication
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY Fluendo.FluendoPlatform.Infrastructure.Authentication/Fluendo.FluendoPlatform.Infrastructure.Authentication.csproj Fluendo.FluendoPlatform.Infrastructure.Authentication/
COPY Fluendo.FluendoPlatform.Infrastructure.Common/Fluendo.FluendoPlatform.Infrastructure.Common.csproj Fluendo.FluendoPlatform.Infrastructure.Common/
RUN dotnet restore Fluendo.FluendoPlatform.Infrastructure.Authentication/Fluendo.FluendoPlatform.Infrastructure.Authentication.csproj
COPY . .
WORKDIR /src/Fluendo.FluendoPlatform.Infrastructure.Authentication
RUN dotnet build Fluendo.FluendoPlatform.Infrastructure.Authentication.csproj -c Release -o /app/authentication

FROM build AS publish
RUN dotnet publish Fluendo.FluendoPlatform.Infrastructure.Authentication.csproj -c Release -o /app/authentication

FROM base AS final
WORKDIR /app/authentication
COPY --from=publish /app/authentication .
ENTRYPOINT ["dotnet", "Fluendo.FluendoPlatform.Infrastructure.Authentication.dll"]