version: '3.1'
services:
  # mongo:
    # container_name: fluendo_mongo
    # image: mongo
    # restart: always
    # ports:
      # - 27017:27017
  auth_webapi:
    container_name: flundo_authentication_webapi
    build:
      context: .
      dockerfile: Dockerfile_Authentication
    restart: always
    ports:
      - "5006:5006"
  core_webapi:
    container_name: fluendo_core_webapi
    build:
      context: .
      dockerfile: Dockerfile_Core
    restart: always
    ports:
      - "5007:5007"
  stats_service_webapi:
    container_name: fluendo_statsservice_webapi
    build:
      context: .
      dockerfile: Dockerfile_Stats
    restart: always
    ports:
      - "5009:5009"
    # depends_on:
      # - mongo
