FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app/statsservice
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY Fluendo.FluendoPlatform.StatsService.WebApi/Fluendo.FluendoPlatform.StatsService.WebApi.csproj Fluendo.FluendoPlatform.StatsService.WebApi/
COPY Fluendo.FluendoPlatform.StatsService.Services/Fluendo.FluendoPlatform.StatsService.Services.csproj Fluendo.FluendoPlatform.StatsService.Services/
COPY Fluendo.FluendoPlatform.StatsService.Dal/Fluendo.FluendoPlatform.StatsService.Persistence.csproj Fluendo.FluendoPlatform.StatsService.Dal/
COPY Fluendo.FluendoPlatform.Infrastructure.Common/Fluendo.FluendoPlatform.Infrastructure.Common.csproj Fluendo.FluendoPlatform.Infrastructure.Common/
COPY Fluendo.FluendoPlatform.Infrastructure.Resources/Fluendo.FluendoPlatform.Infrastructure.Resources.csproj Fluendo.FluendoPlatform.Infrastructure.Resources/
RUN dotnet restore Fluendo.FluendoPlatform.StatsService.WebApi/Fluendo.FluendoPlatform.StatsService.WebApi.csproj
COPY . .
WORKDIR /src/Fluendo.FluendoPlatform.StatsService.WebApi
RUN dotnet build Fluendo.FluendoPlatform.StatsService.WebApi.csproj -c Release -o /app/statsservice

FROM build AS publish
RUN dotnet publish Fluendo.FluendoPlatform.StatsService.WebApi.csproj -c Release -o /app/statsservice

FROM base AS final
WORKDIR /app/statsservice
COPY --from=publish /app/statsservice .
ENTRYPOINT ["dotnet", "Fluendo.FluendoPlatform.StatsService.WebApi.dll"]