version: '3.1'
services:
  mongo:
    container_name: fluendo_mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
